// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error)
	GetProductViewByID(ctx context.Context, id pgtype.UUID) (ProductsView, error)
	GetUserViewByID(ctx context.Context, id pgtype.UUID) (UsersView, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpsertProductView(ctx context.Context, arg UpsertProductViewParams) error
	UpsertUserView(ctx context.Context, arg UpsertUserViewParams) error
}

var _ Querier = (*Queries)(nil)
