// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, user_id, product_id, quantity, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, product_id, quantity, status, created_at, updated_at
`

type CreateOrderParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ProductID pgtype.UUID        `json:"product_id"`
	Quantity  int32              `json:"quantity"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.ProductID,
		arg.Quantity,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, product_id, quantity, status, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductViewByID = `-- name: GetProductViewByID :one
SELECT id, name, price, quantity FROM products_view WHERE id = $1
`

func (q *Queries) GetProductViewByID(ctx context.Context, id pgtype.UUID) (ProductsView, error) {
	row := q.db.QueryRow(ctx, getProductViewByID, id)
	var i ProductsView
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Quantity,
	)
	return i, err
}

const getUserViewByID = `-- name: GetUserViewByID :one
SELECT id, username, email FROM users_view WHERE id = $1
`

func (q *Queries) GetUserViewByID(ctx context.Context, id pgtype.UUID) (UsersView, error) {
	row := q.db.QueryRow(ctx, getUserViewByID, id)
	var i UsersView
	err := row.Scan(&i.ID, &i.Username, &i.Email)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, product_id, quantity, status, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProductView = `-- name: UpsertProductView :exec
INSERT INTO products_view (id, name, price, quantity)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    price = EXCLUDED.price,
    quantity = EXCLUDED.quantity
`

type UpsertProductViewParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Price    int64       `json:"price"`
	Quantity int32       `json:"quantity"`
}

func (q *Queries) UpsertProductView(ctx context.Context, arg UpsertProductViewParams) error {
	_, err := q.db.Exec(ctx, upsertProductView,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Quantity,
	)
	return err
}

const upsertUserView = `-- name: UpsertUserView :exec
INSERT INTO users_view (id, username, email)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE
SET username = EXCLUDED.username,
    email = EXCLUDED.email
`

type UpsertUserViewParams struct {
	ID       pgtype.UUID `json:"id"`
	Username string      `json:"username"`
	Email    string      `json:"email"`
}

func (q *Queries) UpsertUserView(ctx context.Context, arg UpsertUserViewParams) error {
	_, err := q.db.Exec(ctx, upsertUserView, arg.ID, arg.Username, arg.Email)
	return err
}
