// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error)
	UpdateInventory(ctx context.Context, arg UpdateInventoryParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
